### ISSUE TITLE
Investigate MessageVPNLimits monitor and its associated dataviews disappearing from ActiveConsole

### ISSUE THREAD

**Issue by itsJamilAhmed** [SolaceLabs/solgeneos-custom-monitors#6]
It has been reported that the dataviews called '**MessageVPNLimits**' and '**BrokerLimits**', as generated by the **MessageVPNLimits** custom monitor, occasionally disappear from the ActiveConsole GUI view.  

(Internal ref: RT61761)

**Comment by itsJamilAhmed** [comment]
**Summary of findings:**
1. A restart of the SolGeneos agent promptly restores the monitor and dataviews. (Using `/bin/systemctl restart solgeneos`)
2. `solgeneosagent.log` shows a `NullPointerException`, potentially the point at which the monitor stops further updates. 
3. The `NullPointerException` is preceded by a period of no connectivity to the ITRS Gateway, then an error in postInitialize(), and finally an error again in onCollect().
   a. Initial log entries:  `MessageVPNLimitsMonitor - Error in calling monitor onReport() - Exception when report to np0 for BrokerLimits(brokerLimits): Error executing command "#redacted#.SolaceSampler.signOn" with parameters [60] - There is no Gateway connected`
  b. Followed by: `MessageVPNLimitsMonitor - Error in postInitialize()`
  c. Then: `MessageVPNLimitsMonitor - Error in calling monitor onCollect() - Connection refused (Connection refused)`
  d. Lastly: `MessageVPNLimitsMonitor - Error in calling monitor onCollect() - NullPointerException`

**Next Steps:**
1. Reproduce behaviour reliably to determine condition leading to `NullPointerException` in the onCollect()
2. Catch the exception and recover in a way to not leave the monitor in a failed state.

**Comment by itsJamilAhmed** [comment]
In the lab environment, the following log conditions can be reproduced:
1. `MessageVPNLimitsMonitor - Error in calling monitor onReport() - Exception when report to np0 for BrokerLimits(brokerLimits): Error executing command "emea5-MW.SolaceSampler.signOn" with parameters [60] - There is no Gateway connected`
     - By shutting down the ITRS Gateway
2. `ERROR [com.solacesystems.solgeneos.custommonitors.MessageVPNLimitsMonitor] MessageVPNLimitsMonitor - Error in calling monitor onCollect() - Connection refused (Connection refused)`
`ERROR [com.solacesystems.solgeneos.custommonitors.MessageVPNLimitsMonitor] java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)`
    - By shutting down the SEMP service
3. `MessageVPNLimitsMonitor - Error in postInitialize()`
    - By restarting the agent when SEMP service is shutdown
4.  `NullPointerException`
    - By enabling the SEMP service again after the agent has started following step 3 above. 

Full stack trace of the `Error in postInitialize()` also shows it to be somewhere in the socket connectivity logic as triggered by `org.apache.http.impl.client` when a SEMP query is executed.

`ERROR [com.solacesystems.solgeneos.custommonitors.MessageVPNLimitsMonitor] MessageVPNLimitsMonitor - Error in postInitialize()
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at com.solacesystems.solgeneos.custommonitors.MessageVPNLimitsMonitor.submitSEMPQuery(MessageVPNLimitsMonitor.java:268)
        at com.solacesystems.solgeneos.custommonitors.MessageVPNLimitsMonitor.setBrokerLimits(MessageVPNLimitsMonitor.java:291)
        at com.solacesystems.solgeneos.custommonitors.MessageVPNLimitsMonitor.onPostInitialize(MessageVPNLimitsMonitor.java:240)
        at com.solacesystems.solgeneos.solgeneosagent.monitor.BaseMonitor.initialize(BaseMonitor.java:228)
        at com.solacesystems.solgeneos.solgeneosagent.SolGeneosAgent.start(SolGeneosAgent.java:579)
        at com.solacesystems.solgeneos.solgeneosagent.SolGeneosAgent.main(SolGeneosAgent.java:682)
`

So this is less to do with the custom monitor code, and more behaviour in the framework. The reason this particular monitor is susceptible is because it does some SEMP querying in the `postInitialize()`, whereas the others just do SEMP queries exclusively inside `onCollect()`.

It is clear that a particularly rare set of conditions is leading to this issue manifesting.

The SEMP querying done in `postInitialize()` by calling `setBrokerLimits()` is to set the object `Map<String, Integer> brokerLimitsLookup` with values. This object then is accessed by all subsequent calls to `onCollect()`.
If this fails to actually initialize appropriately because the SEMP call failed (such as the service being inaccessible or not ready), then the monitor fails to recover operation again.

An appropriate fix would be to detect this object as not being in a populated state and try to initialize it again with a repeat call to `setBrokerLimits()`.

**Comment by itsJamilAhmed** [comment]
It's worth noting that the object `brokerLimitsLookup` is a `Map<String, Integer>` that gets populated in `postInitialize()` and referenced each time when `onCollect()` is called. 

If the SEMP query done in `onPostInitialize()` -> `setBrokerLimits()` fails for any reason, no further checks are done to detect this or try again to populate `brokerLimitsLookup`.

This is a defensive step that should be added to the monitor code to prevent the `NullPointerException` and can close off this issue.

**Comment by itsJamilAhmed** [comment]
Fix has been tested and the disappearing dataviews condition along with the `NullPointerException` error message no longer occurs.

Any users of the `1.0` version of the MessageVPNLimits Monitor are encouraged to build and deploy the new `1.1` version.
Following the `ant dist` step 7 from the [usage instructions](https://github.com/SolaceLabs/solace-custom-monitor-solgeneos#how-to-use-this-repository), the newly built Jar file `./_antDist/lib/custommonitors-vpnlimits.jar` can replace the existing file already deployed to `/usr/sw/solgeneos/monitors` on the appliances.
